---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
        exclude_types: [svg, plain-text]
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ['--config=pyproject.toml']
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==23.7.0
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        language: python
        language_version: python3.11
        types: [python]
        additional_dependencies:
          - flake8-black>=0.2.2
          - flake8-mutable
          - flake8-gl-codeclimate
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-print
          - flake8-simplify
          - flake8-django
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.16.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.0"]
        types: [python]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
