# Generated by Django 5.0.3 on 2024-03-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('azbankgateways', '0004_auto_20211115_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_type',
            field=models.CharField(
                choices=[
                    ('BMI', 'BMI'),
                    ('SEP', 'SEP'),
                    ('ZARINPAL', 'Zarinpal'),
                    ('IDPAY', 'IDPay'),
                    ('ZIBAL', 'Zibal'),
                    ('BAHAMTA', 'Bahamta'),
                    ('MELLAT', 'Mellat'),
                    ('PAYV1', 'PayV1'),
                ],
                max_length=50,
                verbose_name='Bank',
            ),
        ),
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='status',
            field=models.CharField(
                choices=[
                    ('WAITING', 'Waiting'),
                    ('REDIRECT_TO_BANK', 'Redirect to bank'),
                    ('RETURN_FROM_BANK', 'Return from bank'),
                    ('CANCEL_BY_USER', 'Cancel by user'),
                    ('EXPIRE_GATEWAY_TOKEN', 'Expire gateway token'),
                    ('EXPIRE_VERIFY_PAYMENT', 'Expire verify payment'),
                    ('COMPLETE', 'Complete'),
                    ('ERROR', 'Unknown error acquired'),
                ],
                max_length=50,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='bank',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
