# Generated by Django 5.0.1 on 2024-01-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azbankgateways", "0004_auto_20211115_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="bank_type",
            field=models.CharField(
                choices=[
                    ("BMI", "BMI"),
                    ("SEP", "SEP"),
                    ("ZARINPAL", "Zarinpal"),
                    ("IDPAY", "IDPay"),
                    ("ZIBAL", "Zibal"),
                    ("BAHAMTA", "Bahamta"),
                    ("MELLAT", "Mellat"),
                    ("PAYV1", "PayV1"),
                ],
                max_length=50,
                verbose_name="Bank",
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Waiting"),
                    ("Redirect to bank", "Redirect to bank"),
                    ("Return from bank", "Return from bank"),
                    ("Cancel by user", "Cancel by user"),
                    ("Expire gateway token", "Expire gateway token"),
                    ("Expire verify payment", "Expire verify payment"),
                    ("Complete", "Complete"),
                    ("Unknown error acquired", "Unknown error acquired"),
                ],
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
