---

name: Linters

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pre-commit-linter:
    name: pre-commit-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install pre-commit
      - name: linter
        run: >-
          pre-commit run --color always --all-files
          -s ${GITHUB_BASE_REF_SHA} -o HEAD
        env:
          GITHUB_BASE_REF_SHA: ${{ github.event.pull_request.base.sha }}
